### PR TITLE
Remove Fabric API Dependency and update .gitignore

### PR DESCRIPTION
**Pull request by valoeghese**
I noticed you depend on fabric api when the mod doesn't even utilise fabric api in the code

The only time you'd really want fabric api installed is for Fabric-Resource-Loader so your lang files are loaded. But since Mod Menu requires fabric api in the first place users will already have fabric api installed when your lang files need to be loaded (since I think the only time you have your config gui is when mod menu is loaded).

Also updated gitignore to ignore eclipse ide files

### CODE REVIEW

**Comment by valoeghese** [comment]
If I missed something please let me know

**Comment by dorianpb** [comment]
lol sorry about the .gitignore i dont use eclipse and kinda forgot it was a thing

your logic about not strictly depending on fabric api makes a lot of sense; i honestly kinda forgot it was a thing i might need to depend on

ill probably merge this after i get around to testing it first

thanks for the support!

**Comment by valoeghese** [comment]
Yep, I'm now running a modified version of the mod (i.e. the version on my fork) when I actually play the game, and it works perfectly, at least for the resource pack I'm using :)

**Comment by dorianpb** [comment]
ok it turns out fabric api is needed to actually build the mod so we're going to have to keep it in the build.gradle and gradle.properies but ill keep everything else

**Pull request merged**
